import '../../styles/admin/admin.css'

export const metadata = {
  title: 'Admin - ChineduCode',
  description: 'Generated by Next.js',
}
 
export default function AdminLayout({ children }) {
  return (
    <main>
      {children}
    </main>
  )
}
